config/routes.rb
MobilePayWithBlockchain::Application.routes.draw do
  get "blocks/index"
  get "blocks/:id/show" => 'blocks#show', as: :blocks_show

  resources :payments do
    member do
      get 'reject'
    end
  end

  get "home/index"
  devise_for :users

  root 'payments#index'

end

app/models/block.rb
class Block < ActiveRecord::Base
  belongs_to :block_worker
  delegate :block_hash, :merkle_root, :previous_block_hash, :payment_count, :timestamp, :nonce, :to => :block_worker
  
  has_many :payments
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  def index
    @blocks = Block.all.order(:created_at).reverse_order.limit(10)
  end
  
  def show
    @block = Block.find params[:id]
  end
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/views/blocks/index.html.erb
<h1>Recent blocks</h1>

<table>
  <tr>
    <th>id</th>
    <th>Transactions</th>
    <th>block hash</th>
    <th>nonce</th>
    <th>Timestamp</th>
    <th>Previous block hash</th>
  </tr>
  
  <% @blocks.each do |block| %>
    <tr>
      <td><%= block.id %></td>
      <td><%= block.payment_count %></td>
      <td><%= block.block_hash %></td>
      <td><%= block.nonce %></td>
      <td><%= block.timestamp.to_i %></td>
      <td><%= block.previous_block_hash %></td>
      <td><%= link_to 'detail', blocks_show_path(block.id) %></td>
    </tr>
  <% end %>
</table>

app/views/blocks/show.html.erb
<h2>Block detail</h2>

<p>
  <span class="blfield">Id</span>
  <span class="blvalue"><%= @block.id %></span>
<br/>
  <span class="blfield">Timestamp</span>
  <span class="blvalue"><%= @block.timestamp.to_i %></span>
  
<br/>
  <span class="blfield">Transaction count</span>
  <span class="blvalue"><%= @block.payment_count %></span>
  
<br/>
  <span class="blfield">Timestamp</span>
  <span class="blvalue"><%= @block.timestamp.to_i %></span>
  
<br/>
  <span class="blfield">nonce</span>
  <span class="blvalue"><%= @block.nonce %></span>
  
<br/>
  <span class="blfield">Merkle root</span>
  <span class="blvalue"><%= @block.merkle_root %></span>
  
<br/>
  <span class="blfield">Block hash</span>
  <span class="blvalue"><%= @block.block_hash %></span>
  
<br/>
  <span class="blfield">Previous block hash</span>
  <span class="blvalue"><%= @block.previous_block_hash %></span>
  
<br/>
  <span class="blfield">Timestamp</span>
  <span class="blvalue"><%= @block.timestamp.to_i %></span>
</p>

<h3>Transactions</h3>
<table>
<thead>
    <tr>
      <th>Merchant</th>
      <th>Currency</th>
      <th>Pre approval</th>
      <th>Accepted?</th>
      <th>Transaction hash</th>
      <th>Image hash</th>
    </tr>
  </thead>

  <tbody>
    <% @block.payments.each do |payment| %>
      <tr>
        <td><%= payment.merchant %></td>
        <td><%= payment.currency %></td>
        <td><%= payment.pre_approval %></td>
        <td><%= if payment.approval_status == true then 'Yes' else 'REJECTED!!!' end %></td>
        <td><%= payment.transaction_hash %></td>
        <td><%= payment.image_hash %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</table>