config/routes.rb
MobilePayWithBlockchain::Application.routes.draw do
  get "blocks/index"
  get "blocks/:id/show" => 'blocks#show', as: :blocks_show

  resources :payments do
    member do
      get 'reject'
    end
  end

  get "home/index"
  devise_for :users

  root 'payments#index'

end

app/models/payment.rb
require 'digest'

class Payment < ActiveRecord::Base
  belongs_to :user
  belongs_to :block
  has_attached_file :invoice, :default_url => "/images/invoices/missing.png"
  #validates :invoice, :attachment_presence => true Commented out because I can't figure out how to run tests with it in place!
  validates_attachment :invoice, content_type: { :content_type => ["image/jpg", "image/tif", "image/png", 'application/pdf'] }
  after_create :hash_transaction, :hash_image
  
  CURRENCIES = ['USD', 'EUR', 'BTC', 'INR', 'AUD', 'CAD', 'JPY']

  # TODO: Convert currencies so limits make sense!
  # TODO: WHY is this not an after create or even before save item?
  def apply_rules
    self.approval_status = (amount.to_f < user.limit.to_f)
    save
  end
  
  def to_h
    {
      merchant: self.merchant,
      amount: self.amount,
      currency: self.currency,
      image_hash: self.image_hash,
      user_id: self.user_id
    }
  end
  
  private
  
  # creates hash of transaction that will be fed into block
  def hash_transaction
    dig = Digest::SHA256.new
    [user_id, merchant, currency, amount, created_at, image_hash ].each do |thing|
      dig << thing.to_s
    end
    
    self.transaction_hash = dig.to_s
    save
  end
  
  def hash_image
    return if invoice.nil? || invoice.path.nil? ## this is just for testing. 
    f = File.open(invoice.path, "rb")
    dig = Digest::SHA256.new
    f.each_byte do |by|  # doing it one byte at a time is horribly slow on large files.
  
      dig << by.to_s 
    end

    # Never modify an existing image, in case of tampering
    self.image_hash ||= dig.to_s
    save
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_payment, only: [:show, :edit, :update, :destroy, :reject]

  # GET /payments
  # GET /payments.json
  def index
    @payments = current_user.payments
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)
    
    respond_to do |format|
      if @payment.save
        @payment.apply_rules
        if @payment.approval_status == true            
          format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
          format.json { render action: 'show', status: :created, location: @payment }
          
        else
          format.html { redirect_to reject_payment_path @payment }    
        end
      else
        format.html { render action: 'new' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end
  
  def reject
    
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def payment_params
    params.require(:payment).permit(:user_id, :merchant, :currency, :comment, :pre_approval, :amount, :invoice)
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for @payment, html: { :multipart => true } do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, value: current_user.id %>
  
  <div class="field">
    <%= f.label :merchant %><br>
    <%= f.text_field :merchant, size: 40 %>
  </div>
  <div class="field">
    <%= f.label :currency %><br>
    <%= f.select :currency, Payment::CURRENCIES %>
  </div>
  <div class="field">
    <%= f.label :pre_approval %><br>
    <%= f.check_box :pre_approval %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment, size: 40, limit: 40 %>
  </div>
  
  <div class="field">
    <%= f.label :invoice %>
    <%= f.file_field :invoice %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<h1>Listing payments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Merchant</th>
      <th>Currency</th>
      <th>Pre approval</th>
      <th>Accepted?</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.user.email %></td>
        <td><%= payment.merchant %></td>
        <td><%= payment.currency %></td>
        <td><%= payment.pre_approval %></td>
        <td><%= if payment.approval_status == true then 'Yes' else 'REJECTED!!!' end %></td>
        <td><%= link_to 'Show', payment %></td>
        <!-- hide invalid actions.
          <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
          <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/reject.html.erb
<h2>Warning! This payment is over your limit and will be rejected!</h2>

<p>Details</p>
<p>
  <strong>Merchant:</strong>  <%= @payment.merchant %><br/>
  <!-- display needs to take into account non-US currency -->
  <strong>Amount:</strong>  <%= number_to_currency @payment.amount  %><br/>
  <strong>Your limit:</strong>  <%= number_to_currency @payment.user.limit %><br/>
</p>

<p><%= link_to 'home', root_path %></p>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @payment.user_id %>
</p>

<p>
  <strong>Merchant:</strong>
  <%= @payment.merchant %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @payment.currency %>
</p>

<p>
  <strong>Pre approval:</strong>
  <%= @payment.pre_approval %>
</p>

<p>
  <strong>Transaction hash:</strong>
  <%= @payment.transaction_hash %>
</p>

<p>
  <strong>Image hash:</strong>
  <%= @payment.image_hash %>
</p>

<p>
  <strong>Image:</strong><br/>
  <%= image_tag @payment.invoice.url %>
</p>

<h3>This payment has been <% if @payment.approval_status == true %>'Accepted'<% else %><span style="color: red;">REJECTED</span><% end %></h3>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>